### ISSUE TITLE
Magento 1.9.2.0 + patch SUPEE-6285 Patch

### ISSUE THREAD

**Issue by ihor-sviziev** [bragento/magento-core#20]
Please add Magento 1.9.2.0 to repo.
http://merch.docs.magento.com/ce/user_guide/Magento_Community_Edition_User_Guide.html#magento/release-notes-ce-1.9.2.html

Also available new security patch SUPEE-6285 Patch Bundle.

https://www.magentocommerce.com/download

**Comment by Julime** [comment]
:+1:

**Comment by davidverholen** [comment]
Hey, currently I'm on vacation, will add this next week

**Comment by ihor-sviziev** [comment]
@davidverholen thank you!

**Comment by davidverholen** [comment]
no Problem, but it wasn't me ;) A colleague updated the repo last week
