### ISSUE TITLE
local.xml in version 1.9.2.0

### ISSUE THREAD

**Issue by flancer64** [bragento/magento-core#23]
Hello, guys.

Should we have [local.xml](https://github.com/bragento/magento-core/blob/1.9.2.0/app/etc/local.xml) file in the 1.9.2.0 package?

My installation script tries to use {{...}} parameters to create new connection instead of to parse command line parameters.

I will remove local.xml before installation script startup - this should solve my problem, I suppose.

Thanks for you packages :)

Regards,

Alex.

**Comment by davidverholen** [comment]
hm your right, just downloaded magento to be sure :)
this file should not be there

**Comment by davidverholen** [comment]
to still have the right base Version I just changed the tag to the new commit (pls don't do this at home)
you may have to remove Magento from your vendor dir to force a reinstallation
