### ISSUE TITLE
Update to 1.9.2.1 + SUPEE-6482

### ISSUE THREAD

**Issue by Grohotun** [bragento/magento-core#24]
Again new patch...

**Comment by hostep** [comment]
You might want to hold of applying the patch for a few hours, some guy is claiming the patch is incomplete:
http://community.magento.com/t5/Version-Upgrades/Magento-SUPEE-6482-partial-patch-released/m-p/12772#U12772

**Comment by davidverholen** [comment]
ok, I just updated to 1.9.2.1 but will wait with the patch for now

**Comment by Grohotun** [comment]
Nice.
How about patching other versions of magento?

**Comment by hostep** [comment]
Magento updated their release notes and now claims the CE patches were intended to only patch 2 issues with the SOAP stuff.

There is an interesting discussion going on about it in this thread:
http://community.magento.com/t5/Version-Upgrades/Magento-SUPEE-6482-partial-patch-released/m-p/12772#U12772

But I think its best to apply the patch anyway, and if Magento does turn around its decision, they will probably release yet another patch (or maybe a v2 of this one), but not sure how long that will take.

**Comment by Grohotun** [comment]
Yes, it's better to apply this patch

**Comment by davidverholen** [comment]
this patch can't be applied to 1.9.2.1. It's only for <=1.9.2.0.
Still it has to be applied to all other Versions, but currently I don't have the time

**Comment by Grohotun** [comment]
Ok, make it when you can)
