### ISSUE TITLE
PATCH 389

### ISSUE THREAD

**Issue by samuelecarpene** [bragento/magento-core#26]
In all version is missing the PATCH 389
https://gist.github.com/piotrekkaminski/c348538ca91ba35773be
that solve a bug in core_url_rewrite record generation.

I have tested in some magento installation and i found in all this bug.

Read this.
http://magento.stackexchange.com/questions/32159/core-url-rewrite-bug-in-magento-1-8
or this
http://mmenozzi.github.io/2015/09/15/crazy-magento-url-rewrite-generation/

Can you apply this patch to all versions? Or maybe the last patched?

Thank you.

**Comment by davidverholen** [comment]
since this is not an official CE Patch, I think it would be a better approach to fix this Bug in a Module like described here: http://magento.stackexchange.com/questions/17553/magento-core-url-rewrite-table-excessively-large

**Comment by davidverholen** [comment]
https://github.com/daniel-rose/DR_FastCatalogUrlIndexer fixes this and reduces the url rewrites by not indexing deactivated products (this behaviour can be configured)
