### ISSUE TITLE
Magento Enterprise

### ISSUE THREAD

**Issue by brandontamm** [bragento/magento-core#29]
Hi,

I am working on a dockerized-magento project at http://github.com/andreaskoch/dockerized-magento.

The project loads your magneto-core and works perfect. Only problem is, I need Magento Enterprise.

I have hit a roadblock trying to create my own Magento Enterprise repository and calling that from the composer.json file.

Are you willing to take a look at my repo and provide guidance: https://github.com/brandontamm/magento-ee

Private composer repositories are beyond my expertise and I'd be willing to pay for a working Magento Enterprise repository (like the one you have) that I can load Enterprise version from and continue to patch.

Let me know as soon as you can - Thanks!

Brandon Tamm

**Comment by davidverholen** [comment]
Hi @brandontamm,

you might not want to publish the magento ee code. I'm pretty sure, that this violates the EE license.

In Order to install this via composer you need 3 things:
- type in composer.json (for example magento-core)
- an installer Plugin associated to the type (for example old versions of https://github.com/magento-hackathon/magento-composer-installer )

- a mapping which tells the installer, which files and directories are to be copied to the web root (in this repo for example in the composer.json under the extra -> map key)


You might also want to look here: https://github.com/bragento/bragento-composer-installer/issues/24

He seemed to be succesfully installing the ee over composer

**Comment by brandontamm** [comment]
Update -

I am working with a composer.json file that I have modified from: https://github.com/andreaskoch/dockerized-magento.

Original composer file - http://pastebin.com/uCL1iJDZ
My edited composer file - http://pastebin.com/a6hEhQF5
Basically, I had to remove the Magento CE 1.9 from the required dependencies and create a custom repo for Magento Enterprise 1.14 to load as a required dependency. Composer finds my repo and downloads it, however, it is downloading it to the /vendor/ directory instead of the /web directory required by the rest of the project.

This breaks the rest of the project: https://github.com/andreaskoch/dockerized-magento

Anyway, I noticed the "extra" section of the composer file and wondered if it wasn't something simple? Magento CE 1.9 was downloaded to /web and the installer worked perfectly.
Magento EE 1.14 is downloading to /vendor and the installer doesn't work.

Please help! I am willing to donate to you for a quick response to make this work :)

Also, the composer.json from the Magento EE repo is identical to yours.

**Comment by davidverholen** [comment]
composer installs the packages per default in the vendor directory.

the magento-composer-installer plugin does copy the files of packages with type "magento-core" to the directory defined in your composer.json under extra -> magento-root-dir.

To know, which files have to be copied, it uses the extra -> map array in the composer.json of the magento core repo.

so basically, you have to add the extra -> map array to your magento ee core repo like here:
https://github.com/bragento/magento-core/blob/1.9/composer.json#L9, but for all needed folders and files of magento ee.

you can test this for example by only adding the index.php and see if it is deployed to the web dir

**Comment by brandontamm** [comment]
David - thank you for your response and for helping when I can't find anyone else who will.

Anyway, I actually changed the repo from when I first submitted the issue.
https://github.com/brandontamm/magento-ee

I basically duplicated yours and swapped the 1.9 files for the 1.14 files so that mapping is here: https://github.com/brandontamm/magento-core/blob/1.14/composer.json

I still have the issue however - any ideas?

It's like the "extra" section isn't being referenced because I am pulling it from my repo versus the firegento repo. I am completely stuck :(

**Comment by brandontamm** [comment]
Hey - thank you again for your help. I did get it to work. I will be cleaning up the code sometime next week and submitting a pull request for andreas' project at https://github.com/andreaskoch/dockerized-magento 

Cheers! And happy thanksgiving!
